# Generated by Django 6.0.5 on 2026-06-29 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('programme_id', models.AutoField(primary_key=True, serialize=False)),
                ('programme_name', models.CharField(max_length=150)),
                ('programme_description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('programme_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_skills', to='programmes.event')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_skills', to='volunteers.skill')),
            ],
            options={
                'unique_together': {('event', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='required_skills',
            field=models.ManyToManyField(related_name='events', through='programmes.EventSkill', to='volunteers.skill'),
        ),
        migrations.AddField(
            model_name='event',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='programmes.programme'),
        ),
        migrations.AddField(
            model_name='programme',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='programmes.status'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='programmes.status'),
        ),
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('volunteer_role', models.CharField(blank=True, max_length=100)),
                ('attendance', models.BooleanField(default=False)),
                ('assignment_date', models.DateField(auto_now_add=True)),
                ('notify_flag', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='programmes.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
