# Generated by Django 6.0.5 on 2026-06-29 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('report_name', models.CharField(max_length=150)),
                ('satisfaction_score', models.PositiveSmallIntegerField(help_text='Satisfaction score as a percentage (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='programmes.programme')),
            ],
        ),
    ]
