# Generated by Django 6.0.5 on 2026-06-29 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('forename', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('emergency_contact', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('notification_preference', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS / Text'), ('PHONE', 'Phone Call'), ('NONE', 'No Reminders')], default='EMAIL', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100, unique=True)),
                ('skill_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DBSStatus',
            fields=[
                ('dbs_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('dbs_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=15)),
                ('dbs_expiry', models.DateField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbs_statuses', to='volunteers.person')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerSkill',
            fields=[
                ('volunteer_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=15)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_skills', to='volunteers.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
